spring.application.name=middleware-rabbitmq-seckill
spring.profiles.active=mysql,dubbo,discovery,amqp


#报异常的时候，消息重试次数为1
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=1
