dubbo.registry.address=nacos://192.168.8.188:8848
dubbo.protocol.port=-1
dubbo.protocol.name=dubbo
dubbo.application.name=${spring.application.name}-dubbo


dubbo.application.qos-enable=false
dubbo.application.serialize-check-status=WARN
