server.port=4006
spring.application.name=middleware-gateway
spring.profiles.active=discovery


spring.cloud.gateway.discovery.locator.enabled=false
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#mapper
spring.cloud.gateway.routes[0].id=banner
spring.cloud.gateway.routes[0].uri=lb://frontend-banner
spring.cloud.gateway.routes[0].predicates[0]=Path=/banner
#热销产品
spring.cloud.gateway.routes[1].id=hotProduct
spring.cloud.gateway.routes[1].uri=lb://frontend-hot
spring.cloud.gateway.routes[1].predicates[0]=Path=/hotProduct
spring.cloud.gateway.routes[1].predicates[1]=Query=city
#热门服务
spring.cloud.gateway.routes[2].id=recommendation
spring.cloud.gateway.routes[2].uri=lb://frontend-hot
spring.cloud.gateway.routes[2].predicates[0]=Path=/recommendation
spring.cloud.gateway.routes[2].predicates[1]=Query=city

spring.cloud.gateway.routes[3].id=search
spring.cloud.gateway.routes[3].uri=lb://frontend-search
spring.cloud.gateway.routes[3].predicates[0]=Path=/search


spring.cloud.gateway.routes[4].id=details
spring.cloud.gateway.routes[4].uri=lb://frontend-details
spring.cloud.gateway.routes[4].predicates[0]=Path=/details

spring.cloud.gateway.routes[5].id=comment
spring.cloud.gateway.routes[5].uri=lb://frontend-feedback
spring.cloud.gateway.routes[5].predicates[0]=Path=/comment

spring.cloud.gateway.routes[6].id=sendyzm
spring.cloud.gateway.routes[6].uri=lb://frontend-login
spring.cloud.gateway.routes[6].predicates[0]=Path=/sendyzm

spring.cloud.gateway.routes[7].id=login
spring.cloud.gateway.routes[7].uri=lb://frontend-login
spring.cloud.gateway.routes[7].predicates[0]=Path=/login

spring.cloud.gateway.routes[8].id=buytime
spring.cloud.gateway.routes[8].uri=lb://frontend-seckill
spring.cloud.gateway.routes[8].predicates[0]=Path=/buytime

spring.cloud.gateway.routes[9].id=buyaction
spring.cloud.gateway.routes[9].uri=lb://frontend-seckill
spring.cloud.gateway.routes[9].predicates[0]=Path=/buyaction

spring.cloud.gateway.routes[10].id=order
spring.cloud.gateway.routes[10].uri=lb://frontend-order
spring.cloud.gateway.routes[10].predicates[0]=Path=/order

spring.cloud.gateway.routes[11].id=feedback
spring.cloud.gateway.routes[11].uri=lb://frontend-feedback
spring.cloud.gateway.routes[11].predicates[0]=Path=/feedback