spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/livegoods
spring.datasource.username=root
spring.datasource.password=123456

#mybatis
mybatis.type-aliases-package=com.tz.pojo
mybatis.mapper-locations=classpath:mybatis/**/*.xml
##加载当前项目或其他项目中名称为application-mysql.properties
#spring.profiles.active=mysql